### ISSUE TITLE
[Feature]: 이스터 에그 작성하기

### ISSUE THREAD

**Issue by KJH622** [Kim-Yeon-ho/2023_SoftwareEng01#11]
💡 Feature 설명
특정 숫자가 입력되는 순간 특정 메시지가 출력됩니다.

🙏 Prepare Issue(Optional)
No response

⭐️ 우선순위
★

💁 예상 작업 기간
~ 11/12

🙋실제 작업 기간(PR 작성 직전에 수정)
~ 11/14

**Comment by Kim-Yeon-ho** [comment]
👍
