### ISSUE TITLE
[Feature]: 테스트 케이스로 factrial 함수 구현 중 문제

### ISSUE THREAD

**Issue by dlwngud629** [Kim-Yeon-ho/2023_SoftwareEng01#25]
### 💡 Feature 설명
factrial 함수는 expression을 입력 받아서 len를 확인한 후 정수, 음수, 소수, 기호 등의 예외처리를 합니다. 근데 정수를 입력하는 테스트 케이스에서 AttributeError: 'int' object has no attribute 'replace' 에러가 뜨는데 왜 발생하는지 모르겠습니다. 아래는 테스트케이스입니다.

def factorial(expression):
    if len(str(expression).split()) > 1:
        return "[ERROR] Input Error"
    expression_no_space = expression.strip()
    if not str(expression_no_space).isdigit():
        return "[ERROR] Out Of Range"
    return "=" + str(math.factorial(int(expression_no_space)))

def testPositive(self):
        self.assertEqual(factorial(5),"=120")
def testZero(self):
        self.assertEqual(factorial(0),"=1")
def testNegative(self):
        self.assertEqual(factorial(-1),"[ERROR] Out Of Range")

### ⭐️ 우선순위

★★★★★

### 💁 예상 작업 기간

~12.15(금)

**Comment by kevlarunit** [comment]
자료형 때문에 에러가 발생하는 거 같습니다. expression을 형변환 하지 않고 사용하면 되지 않을까요 ?

**Comment by dlwngud629** [comment]
> 자료형 때문에 에러가 발생하는 거 같습니다. expression을 형변환 하지 않고 사용하면 되지 않을까요 ?

형변환 문제인거 같아서 expression_no_space = str(expression).strip() 형변환을 사용하니 유닛 테스트를 통과했습니다. 이미 expression 파라미터가 string일텐데 string을 string으로 형 변환하는게 이상하네요. 추가로 strip() 함수도 찾아보니 함수 return 값 문제는 아닌듯 합니다.

**Comment by jeon-seong-hyuk** [comment]
저기 테스트유닛에 factorial()에 정수로 집어 넣어져 있는 거 같은데 한번 스트링으로 넣어보시겠어요?

**Comment by Kim-Yeon-ho** [comment]
저희 코드가 입력 처리를 정수가 아닌 string으로 처리하는데 저도 아마 그 문제 같습니다!

**Comment by KJH622** [comment]
자료형 때문에 오류가 생기는거 같습니다. 그 부분을 수정하면 되지 않을까요?

**Comment by dlwngud629** [comment]
저희가 테스트 케이스를 잘 못 만들었네요. expression이 메인 함수에서 string인데 테스트 케이스에선 정수형으로 선언했네요. 
예시로 self.assertEqual(factorial(5),"=120") -> self.assertEqual(factorial('5'),"=120")로 바꿔야 옳게 출력됩니다!

**Comment by iiinsk** [comment]
> 저희가 테스트 케이스를 잘 못 만들었네요. expression이 메인 함수에서 string인데 테스트 케이스에선 정수형으로 선언했네요. 예시로 self.assertEqual(factorial(5),"=120") -> self.assertEqual(factorial('5'),"=120")로 바꿔야 옳게 출력됩니다!

이 부분에서는 fact함수 구현과정에서 (int)expression으로 형변환을 시도해도 괜찮을 것 같습니다.
다만, 기존 cal()함수가 expression을 string으로 받은 후 eval함수를 사용하는 부분이 있어서 string으로 받는게 바람직할 것 같습니다.
