### ISSUE TITLE
[Feature]: 계산기에 사용할 스택 작성하기

### ISSUE THREAD

**Issue by jeon-seong-hyuk** [Kim-Yeon-ho/2023_SoftwareEng01#5]
### 💡 Feature 설명

계산기의 입력을 저장할 공간을 마련하고 후위 연산으로 변경해주기 위한 스택이라는 클래스를 작성합니다.

### ⭐️ 우선순위

★★★★★

### 💁 예상 작업 기간

~11/07

### 🙋실제 작업 기간(PR 작성 직전에 수정)
~11/07

**Comment by Kim-Yeon-ho** [comment]
👍
