### ISSUE TITLE
[Feature]: 나눗셈 연산( / ) 예외처리

### ISSUE THREAD

**Issue by iiinsk** [Kim-Yeon-ho/2023_SoftwareEng01#6]
### 💡 Feature 설명

시스템 입력 중 나누기 연산이 있다면 "Error"를 출력할 수 있도록 예외처리 하는 기능

main함수가 입력을 받을 때 분기문을 통해 우선적으로 예외처리 후 나눗셈연산이 포함되지 않는다면 다음 기능을 수행하도록 구성

사용자가 "="를 입력한 후 "Error"를 출력해야 하므로 이 부분의 흐름에 대해 정립할 필요가 있음.

### ⭐️ 우선순위

★★★

### 💁 예상 작업 기간

~11/12

### 🙋실제 작업 기간(PR 작성 직전에 수정)

~11/14

**Comment by Kim-Yeon-ho** [comment]
라벨링과 project 선택해 주세요
