### ISSUE TITLE
[Feature]: 정수 이외 예외처리 기능 작성하기

### ISSUE THREAD

**Issue by kevlarunit** [Kim-Yeon-ho/2023_SoftwareEng01#7]
### 💡 Feature 설명

정수 이외의 값이 입력됐을 때, 출력값으로 ERROR를 출력하는 예외처리 기능을 작성합니다.

### ⭐️ 우선순위

★★

### 💁 예상 작업 기간

~11/9

### 🙋실제 작업 기간(PR 작성 직전에 수정)

~11/14

**Comment by Kim-Yeon-ho** [comment]
👍
