### ISSUE TITLE
[Feature]: 메인 함수 작성하기

### ISSUE THREAD

**Issue by dlwngud629** [Kim-Yeon-ho/2023_SoftwareEng01#8]
### 💡 Feature 설명

입력, 스택, 예외 처리, 출력을 선언할 수 있는 main함수를 만듭니다.

### ⭐️ 우선순위

★★★★

### 💁 예상 작업 기간

~11/06

### 🙋실제 작업 기간(PR 작성 직전에 수정)

11/13

**Comment by Kim-Yeon-ho** [comment]
작업자 라벨링과 Project 설정 해주세요
